# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = [ { device = "/dev/sda6"; name = "crypted"; } ];
  fileSystems."/".device = "/dev/mapper/crypted";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F2A5-EADF";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
